### ISSUE TITLE
Hide all non-TFC, unobtainable ingots from NEI

### ISSUE THREAD

**Issue by dexman545** [dexman545/technofirma#26]
Hide all the ingots that are impossible to get, or when obtained instantly become their TFC counterpart, e.g., Copper ingots from IC2 and mekanism

**Comment by dexman545** [comment]
OK, fixed, MT had a little hidden function which did this somewhat easily...

**Comment by Elexorien** [comment]
Oh, I was planning on doing that anyway.  But I'll add IC2 to my list as I forgot you added it recently.
